services:
  portfolio:
    build: .
    stdin_open: true
    tty: true

    environment:
      TERM: xterm-256color
      COLORTERM: truecolor

    security_opt:
      - no-new-privileges:true

    cap_drop:
      - ALL

    read_only: true
